title: Enoch Chu
email:
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
profile_logo_url: https://avatars2.githubusercontent.com/u/873915?s=460&v=4
url: ""
twitter_username: ewokchewy
github_username: enochchu
google_analytics: UA-119581577-1

markdown: kramdown
theme: minima
plugins:
    - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - _examples
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
